"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = '{{ .Folder }}'

version = 3

# [transient_prompt]
#   template = ' '
#   foreground = '#FEF5ED'
#   background = 'transparent'

[palette]
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  white = '#FFFFFF'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:pink{{end}}",
    "{{if eq .Code 0}}p:blue{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    powerline_symbol = ''
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = 'p:white'
    background = 'p:blue'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      macos = ' '
      ubuntu = ' '
      windows = ' '

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' ♥ {{ .CurrentDate | date .Format }} '
    foreground = 'p:white'
    background = 'p:blue'
    type = 'time'
    style = 'diamond'

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' CPU: {{ round .PhysicalPercentUsed .Precision }}% | '
    foreground = 'p:white'
    background = 'p:lavender'
    type = 'sysinfo'
    style = 'diamond'

  [[blocks.segments]]
    trailing_diamond = '<transparent,p:lavender></>'
    template = 'RAM: {{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB  '
    foreground = 'p:white'
    background = 'p:lavender'
    type = 'sysinfo'
    style = 'diamond'

  [[blocks.segments]]
    type = "docker"
    style = "diamond"
    leading_diamond = ''
    trailing_diamond = ''
    foreground = "p:white"
    background = "p:lavender"
    template = "  {{ .Context }} "

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .FormattedMs }} '
    foreground = 'p:white'
    background = 'p:os'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = '#000000'
    background = '#ffffff'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a> </> '
      yarn_icon = ' <#348cba></>'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .Full }} '
    foreground = 'p:text'
    background = 'p:lavender'
    type = 'angular'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:text'
    background = 'p:lavender'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '  {{ .Path }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:pink'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_icon = ''
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    template = '  '
    foreground = '#00ff15'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
